blog/urls.py
from django.contrib import admin
from django.urls import path,include
from posts.views import  IndexListView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexListView.as_view(), name='index'),
    path('posts/', include('posts.urls', namespace='posts')), #namespace is for templates: {% POSTS: index %}
    path('users/', include('users.urls', namespace='users')), #namespace is for templates: {% POSTS: index %}
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import IndexListView, PostCreateView, PostPageView, PostDeleteView, PostUpdateView


app_name = 'posts'

urlpatterns = [
    path('category/<int:category_id>/', IndexListView.as_view(), name='category'),
    path('post/<int:post_id>/', PostPageView.as_view(), name='post_page'),
    path('create/', PostCreateView.as_view(), name='create_post'),
    path('update/<int:post_id>/', PostUpdateView.as_view(), name='update_post'),
    path('delete/<int:post_id>/', PostDeleteView.as_view(), name='delete_post'),
    # path('post/<int:post_id>/comment/', CommentCreateView.as_view(), name='add_comment'),
]

users/urls.py
from django.urls import path
from users.views import UserLoginView, UserRegistrationView, UserProfileView, EmailVerificationView
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
]

posts/models.py
from django.db import models
from users.models import User

class PostCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=256)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body=models.TextField()
    image = models.ImageField(upload_to='post_images')
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(to=PostCategory, related_name="posts")



    def __str__(self):
        return f'Title: {self.title} | Author: {self.author}'
    
    class Meta:
        ordering = ['-created_on']

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'Comment by {self.author.username} on {self.post.title}'

posts/forms.py
from django import forms
from .models import Comment, Post, PostCategory

class PostCreateForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
    queryset=PostCategory.objects.all(),
    widget=forms.SelectMultiple(attrs={'class': 'form-control'})
    )
    class Meta:
        model = Post
        fields = ('title', 'body', 'image', 'categories',)
        labels = {
            'body': 'Content', 
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Write your content here...', 'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }
        
class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'image', 'categories',)
        labels = {
            'body': 'Content', 
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Write your content here...', 'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'categories': forms.SelectMultiple(attrs={'class': 'form-control'})
        }
        
class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

        widgets = {
            'content': forms.Textarea(attrs={'rows': 2, 'placeholder': 'Write your comment here...', 'class': 'form-control'}),
        }

posts/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormMixin, CreateView, DeleteView, UpdateView
from django.db.models import Q 
from django.urls import reverse_lazy


from posts.models import Post, PostCategory, Comment
from common.views import TitleMixin
from posts.forms import PostCreateForm, PostUpdateForm, CommentCreateForm


class IndexListView(TitleMixin, ListView):
    model = Post
    template_name = 'posts/index.html'
    title = 'Blog'
    categories = PostCategory.objects.all()

    def get_queryset(self):
        #Filters posts by categories
        queryset = super(IndexListView, self).get_queryset() #queryset is equal to Post.objects.all()
        category_id = self.kwargs.get('category_id')
        search_query = self.request.GET.get('q')  # Get the search query from the request

        if category_id:
            queryset = queryset.filter(categories=category_id)

        if search_query:
            queryset = queryset.filter(
                Q(title__icontains=search_query) | Q(author__username__icontains=search_query)
            )
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context



class PostPageView(TitleMixin, FormMixin, DetailView):
    model = Post
    template_name = 'posts/post_page.html'
    context_object_name = 'post'
    pk_url_kwarg = 'post_id'
    title = 'Blog Page'
    form_class = CommentCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['author'] = self.object.author
        context['body'] = self.object.body
        context['image'] = self.object.image.url if self.object.image else None
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.post = self.object
        form.instance.author = self.request.user  # Assuming the author is the logged-in user
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('posts:post_page', kwargs={'post_id': self.object.id})

class PostCreateView(TitleMixin, CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'posts/post_create.html'  # Create a new template for the form
    success_url = '/'  # Redirect to home page after successful form submission
    title = 'Create New Post'

    def form_valid(self, form):
        form.instance.author = self.request.user  # Set the author of the post to the current user
        return super().form_valid(form)
    
class PostUpdateView(UpdateView):
    template_name = 'posts/post_update.html'
    form_class = PostUpdateForm
    model = Post
    pk_url_kwarg = 'post_id'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('index')
    title = 'Update Post'
    

class PostDeleteView(DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'
    success_url = reverse_lazy("index")

posts/templates/posts/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  {% block css %}
  {% endblock %}
  <link href="{% static 'vendor/css/base.css' %}" rel="stylesheet">
  <script src="https://unpkg.com/htmx.org@1.9.12" integrity="sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2" crossorigin="anonymous"></script>
  <title>{{ title }}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <i class="fa-solid fa-feather-pointed fa-beat" style="color: #63E6BE;"></i>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          {% if user.is_authenticated and user.pk %}
          <a class="nav-link" href="{% url 'users:user_profile' pk=user.pk %}">Profile</a>
          {% endif %}
          <a class="nav-link" href="#">About</a>
        </div>
      </div>
      <div class="navbar-nav">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        {% if user.is_superuser or user.is_staff %}
        <a class="nav-link" href="{% url 'admin:index' %}">Admin Panel</a>
        {% endif %}
        {% else %}
        <a class="nav-link" href="{% url 'users:login' %}">Sign In</a>
        <a class="nav-link" href="{% url 'users:registration' %}">Sign Up</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container-fluid main-wall">
    <div class="row">
      {% block content %}
      <div class="col-12 col-md-8 col-lg-6 mx-auto">
        <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{{ post.image.url }}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/4346f688e5.js" crossorigin="anonymous"></script>
</body>
</html>

posts/templates/posts/index.html
{% extends 'posts/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- Sidebar -->
        <div class="col-12 col-md-3 p-3 d-flex justify-content-center">
            <div class="list-group">
                <h3> Categories </h3>
                {% for category in categories %}
                <div class="cat">
                    <a href="{% url 'posts:category' category_id=category.id %}" class="list-group-item list-group-item-action list-group-item-info" aria-current="true">
                        {{ category.name }}
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- Main Content -->
        <div class="col-12 col-md-6 p-3">
            <div class="list-group">
                {% for post in object_list %}
                <a href="{% url 'posts:post_page' post_id=post.id %}" class="list-group-item-action">
                    <div class="row p-3 position-relative">
                        <div class="col-8">
                            <h1 class="post-title">{{ post.title }}</h1>
                            <h2>Author: <span class="author-name">{{ post.author }}</span></h2>
                            <p>{{ post.created_on }}</p>
                        </div>
                        <div class="col-4 position-relative">
                            <img class="card-img img-fluid" src="{{ post.image.url }}" alt="Post Image">
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>

        <!-- Sidebar -->
        <div class="col-12 col-md-3 p-3">
            <div class="mb-4">
                <form class="d-flex me-2 mt-2" method="GET" action="{% url 'index' %}" role="search">
                    <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-dark" type="submit">Search</button>
                </form>
            </div>
            {% if user.is_authenticated %}
            <div class="d-flex justify-content-center mt-5" style="flex-direction: column;">
                <a href="{% url 'posts:create_post' %}" class="btn btn-outline-success">Create a New Post</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_create.html
{% extends 'posts/base.html' %}
{% load static %}

{% block css %}
<!-- Add any custom CSS here -->
{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center mt-5">
    <div class="card w-100 w-md-50">
        <div class="form-group p-3">
            <div class="card-title nth-card-title">
                <h4>Create Post</h4>
            </div>
            <form method="POST" action="{% url 'posts:create_post' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-flex justify-content-end mt-3">
                    <a href="/" class="btn btn-outline-warning me-2">Cancel</a>
                    <button type="submit" class="btn btn-outline-success">Create Post</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_page.html
{% extends 'posts/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'vendor/css/post.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Optional left column content -->
        <div class="col-12 col-md-3 p-3">
            <!-- Placeholder for potential future content -->
        </div>

        <!-- Main content -->
        <div class="col-12 col-md-6 p-3">
            <div class="container">
                <h1 class="post-title">{{ post.title|safe }}</h1>
                <span class="author-name">Author: {{ post.author }}</span>
                <div class="post-text">{{ post.body|linebreaks }}</div>
                {% if post.image %}
                    <img class="card-img-top img-fluid" src="{{ post.image.url }}" alt="Post image">
                {% endif %}
            </div>
            <br><br>
            <hr>
            {% if user.is_authenticated %}
            <h4>Create Comment</h4>
            <div class="container d-flex justify-content-center mt-5">
                <div class="card w-100">
                    <div class="form-group">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="d-flex justify-content-end">
                                <a href="/" class="btn btn-outline-warning me-2">Cancel</a>
                                <button type="submit" class="btn btn-outline-success">Post</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% endif %}
            <h2>Comments</h2>
            {% if not post.comments.exists %}
                <p>No Comments Yet...</p>
            {% else %}
                {% for comment in post.comments.all %}
                    <strong>{{ comment.author }} - {{ comment.created_on }}</strong>
                    <p>{{ comment.content|linebreaks }}</p>
                {% endfor %}
            {% endif %}
        </div>

        <!-- Right column for actions -->
        <div class="col-12 col-md-3 p-3">
            {% if user.superuser or user.is_staff %}
            <div class="d-flex flex-column">
                <form method="post" action="{% url 'posts:delete_post' post.id %}" class="mb-2">
                    {% csrf_token %}
                    <input type="submit" value="Delete Post" class="btn btn-danger w-100">
                </form>
                <a class="btn btn-warning w-100" href="{% url 'posts:update_post' post.id %}">Update Post</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_update.html
{% extends 'posts/base.html' %}
{% load static %}

{% block css %}
<!-- Add any custom CSS here -->
{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center mt-5">
    <div class="card w-100 w-md-50">
        <div class="form-group p-3">
            <div class="card-title nth-card-title">
                <h4>Update Post</h4>
            </div>
            <form method="POST" action="{% url 'posts:update_post' post_id=post.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-flex justify-content-end mt-3">
                    <a href="/" class="btn btn-outline-warning me-2">Cancel</a>
                    <button type="submit" class="btn btn-outline-success">Update Post</button>
                </div>
            </form>
        </div>
    </div>  
</div>
{% endblock %}